antonioru/beautiful-react-hooks

.nycrc
CHANGELOG.md
package-lock.json
package.json

Adding babel-plugin-istanbul to solve [this issue with istanbul/nyc](https://github.com/istanbuljs/nyc/issues/706)

🍩 Fixing istanbul.js related issues

---

playground/useMediaQuery.md
src/useMediaQuery.js

Typo fix
the demo page for useMediaQuery had a typo in it.

"yet" ->  "yes"

---

README.md

Fixes incorrect URL in readme for useThrottledFn

fix: useThrottledFn.md link in readme

---

CHANGELOG.md
README.md
docs/styleguidist/styleguidist.config.js
docs/useConditionalTimeout.md
package-lock.json
package.json
src/index.js
src/useConditionalTimeout.js
src/useConditionalTimeout.spec.js

An async-utility hook that accepts a callback function, a delay time (in milliseconds) and a condition, then delays the execution of the given function by the defined time when the condition is verified.
closes: #52 
If there's the necessity to run a callback after a certain time and only when a certain condition is verified.

useConditionalTimeout hook

---

CHANGELOG.md
index.d.ts
package.json
src/useConditionalTimeout.js

Adding missing types for the useConditionalTimeout hook
Closes #54

Adding types for useConditionalTimeout

---

docs/useGlobalEvent.md

docs(globalevent): fix typo

---

CHANGELOG.md
README.md
docs/README.zh-CN.md
package.json

Add a Chinese translation of Readme.md
https://github.com/beautifulinteractions/beautiful-react-hooks/issues/69
Oh, I just found it quite useful, want more people to access it easily.
Yes, read twice :P
Added links back and forth

Translation of Readme to Chinese

---

CHANGELOG.md
docs/README.spa-SPA.md

**Description**
Add Spanish Language
**How Has This Been Tested?**
Using Markdown Preview in Vs Code
Screenshots (if appropriate):

Translation of Readme to Spanish

---

README.md

Adding Ukrainian version of README.md file

---

README.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md

Add Brazilian Portuguese translation of README.md file
Help the community, especially those who speak Brazilian Portuguese, in the use of the library.
Using Markdown Preview on Visual Studio Code.

Add Brazilian Portuguese translation

---

CHANGELOG.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.pl-PL.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md
package.json

Adding polish translation to the readme file

add polish translation of readme file

---

CHANGELOG.md
README.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.pl-PL.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md
package.json

fixing polish readme

---

CHANGELOG.md
README.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.pl-PL.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md
docs/styleguidist/styleguidist.config.js
docs/useDrag.md
docs/useDropZone.md
package.json
src/index.js
src/useDropZone.js
src/useDropZone.spec.js

useDropZone

---

CHANGELOG.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.pl-PL.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md
package.json

Fixing links in Contributing section in language specific README files

Fixing links in Contributing section in language specific README files

---

CHANGELOG.md
README.md
docs/useStorage.md
index.d.ts
package.json
src/index.js
src/useStorage.js
src/useStorage.spec.js

Added `useStorage` hook.
An hook to manage `sessionStorage` and `localStorage`
As previously discussed in #82, it would be useful an hook to handle both `sessionStorage` and `localStorage`
- Checked the default value
- Checked the render and the changes in the component.

useStorage

---

src/useInterval.js

https://github.com/beautifulinteractions/beautiful-react-hooks/issues/118
useInterval: cat use return function when clear

feat(useInterval): use return clear interval

---

package-lock.json
src/useConditionalTimeout.js
src/useTimeout.js
src/useViewportSpy.js
test/useConditionalTimeout.spec.js
test/useTimeout.spec.js
test/useViewportSpy.spec.js

changed useTimeout, useViewportSpy and useConditionalTimeout.
* clear timeout when unmout
* check if support api and check if is client in  useViewportSpy
* modify the conditions for clearing in useConditionalTimeout

clear timeout when unmout

---

docs/useObservable.md
index.d.ts
package.json
src/index.js
src/useObservable.js
test/useObservable.spec.js

Add `useObservable` hook
A hook for using `rxjs` observables in react components
Was inspired by how the code looks structured with `rxjs`
- Subscribe and checked single value
- Subscribe and checked multiple values
- Checked the render and the changes in the component.

Add useObservable

---

src/useDefaultedState.js

To streamline the code
Use "??" Instead of determining null and undefined

Optimize the code

---

index.d.ts

fix incorrect typings for hooks using MutableRefObject<T>

---

CHANGELOG.md
index.d.ts
package.json

fixing types

---

CHANGELOG.md
index.d.ts
package.json

Imporving HandlerSetter type

---

CHANGELOG.md
docs/useSwipeEvents.md
index.d.ts
package.json
src/useSwipeEvents.js

Fixing useSwipeEvents types and implementation

---

src/useMediaQuery.js

Commit to fix issue from Safari: mediaQueryList.addeventlistener is not a function

Update useMediaQuery.js for supporting Safari

---

docs/useGeolocation.md

fixed a typo in 'what not to do section'
No issues
Typos are ugly
I came accross the typo while reading the documentation

fixed a small typo in the documentation

---

README.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.jp-JP.md
docs/README.pl-PL.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md
docs/useResizeObserver.md

Update docs + update README.md file with the previously added useCookie hook
#337 
#337 
none
none

docs: update useResizeObserver description

---

.gitignore
src/useTimeout.ts

For now returned array gives the user information about what type is on each element
#374
#374
none
none

fix(types): useTimeout return type

---

README.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.jp-JP.md
docs/README.pl-PL.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md
docs/useMutationObserver.md
package.json
src/useMutationObserver.ts
src/useResizeObserver.ts
test/useMutationObserver.spec.js

Simple hook that watches for changes made to the DOM tree, using a MutationObserver
#329
#329
1. test coverage,
2. docs example,
none

feat(hook): create useMutationObserver hook

---

src/shared/isFunction.ts
src/useConditionalTimeout.ts
src/useDidMount.ts
src/useInfiniteScroll.ts
src/useInterval.ts
src/useResizeObserver.ts
src/useSwipeEvents.ts
src/useTimeout.ts
src/useWillUnmount.ts

From now on, the logic for checking whether a function is a function is commissioned to a dedicated function
DRY principle -> https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
DRY principle -> https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
tests still pass so should still work properly if tests cover these cases
none

refactor: move function check to separate function

---

README.md
docs/README.es-ES.md
docs/README.it-IT.md
docs/README.jp-JP.md
docs/README.pl-PL.md
docs/README.pt-BR.md
docs/README.uk-UA.md
docs/README.zh-CN.md

Update Japanese translation and fix minor mistakes.
- updated Japanese translation
- fixed Japanese docs links and replaced all Japanese emojis 🇯🇵
I've started using this library, so wanted to contribute.

Update Japanese translation docs

---

src/useInterval.ts
src/useTimeout.ts

return type fixed of useInterval and useTimeout.
Issue #402

Issue:402 declaration fixed useInterval and useTimeout

---

.eslintrc.js
.github/workflows/branch-tests.yml
.github/workflows/ci.yml
CHANGELOG.md
docs/useLongPress.md
docs/useMouseEvents.md
src/useEvent.ts
src/useLongPress.ts
test/useLongPress.spec.js

feat(hook): introduces useLongPress hook

---

.github/workflows/ci.yml
CHANGELOG.md
package.json
scripts/generate-exports.js

fix(specifiers): Updates package.json specifiers

---

README.md
docs/README.tr-TR.md

I wanted to let you know that I've contributed to your repository by translating the README file into Turkish. This translation will help the Turkish-speaking community to benefit from your project.
The purpose of translating the README into Turkish is to make the project more accessible to a wider audience. Turkish-speaking users will be able to gain a better understanding of the project's goals and usage.
If you have any feedback or correction requests regarding the translation I've made, please feel free to let me know. I'd be more than happy to make further improvements.
Thank you for providing me with the opportunity to contribute to your project.
Reaching a Wider Audience: By presenting the project in Turkish, you make it more accessible to Turkish-speaking users. This can …

Support tr language

---

package.json

1. Adds React 19 as peer dependency. 
2. It maintains support to React 18.
Closes #429

Add React 19 as peer dependency
