src/useOnlineState.js, src/useOnlineState.spec.js
In general cases, someone who going to use an online hook, is more likely wanna know when does his user's network status be switched to offline, so he can deliver a notice or different content to his users. So it is default to be online.
=> Always be online if the browser does not support online/offline status

CHANGELOG.md, docs/useDebouncedFn.md, docs/useThrottledFn.md, index.d.ts, package.json
Updated `useThrottledFn` and `useDebouncedFn` declarations.
Updated documentation for them.
IDE doesn't show that `useDebouncedFn` or `useThrottledFn` returns `Cancelable` object.
Now we know it and we can use `.cancel()` or `.flush()` methods for cleaning timers.
Make react hooks better, control performance.
=> :bug: :memo: Update cancelable typings.

CHANGELOG.md, package-lock.json, package.json, src/useGeolocationEvents.js, src/useMediaQuery.js, src/useOnlineState.js
Add `typeof window !== 'undefined'` checks to `isSupported`
- Removed a "fixme" `shall this be moved outside the hook?` <- no I guess it shouldn't!
#63 
Solves an issue where using hooks that use `window` fail SSR builds.
Couldn't add unit tests for this.
=> :bug: Fix isSupported when window is not defined

CHANGELOG.md, package.json, src/useLocalStorage.js, src/useLocalStorage.spec.js
Add check to support window object or LocalStorage in the environment. If you use `useLocalStorage` hook with SSR app this causes the application to crash
https://github.com/beautifulinteractions/beautiful-react-hooks/issues/87
Solves an issue where using hooks that use window fail SSR apps.
Couldn't add unit tests for this because when I delete window object all test to crush. But I have been creating test is that `localStorage` not in window object.
=> Fix useLocalStorage hook with SSR

index.d.ts
- Fixes #83 TypeScript: This expression is not callable. Type 'Cancelable' has no call signatures.
#83
=> Update useDebouncedFn type definition

src/useInterval.js
Clear previous interval whem milliseconds changed. This will also allow to stop inteval when null was passed for milliseconds 
https://github.com/beautifulinteractions/beautiful-react-hooks/issues/85
This pull request solves problem with producing new interval when milliseconds chnaged
=> [useInterval] Cleanup previous interval

index.d.ts
The `useLocalStorage` and `useSessionStorage` hooks are now more strongly typed.
```
const defaultFlag: boolean = true;
const [myFlag, setFlag] = useLocalStorage('my-flag', defaultFlag);
// ...later 
setMyFlag('off') <-- Type mismatch, string is not equal to boolean
```
No related issue, but happy to make one if requested 👍 
This helps TypeScript users from having to cast this value, and is more in line with how React's `useState` is typed.
=> Improve types for `useLocalStorage` and `useSessionStorage`

src/utils/isDevelopment.js
This PR makes `isDevelopment` work when `process` is `undefined`.
Webpack 5 doesn't provide a mock of `process`, so the current implementaion causes an error `Uncaught ReferenceError: process is not defined`. This PR fixes the error.
#164
Close #164
I've confirm this PR fixes the error by editting `node_modules/beautiful-react-hooks/esm/utils/isDevelopment.js` directly.
=> fix: isDevelopment error for webpack v5

docs/useGeolocation.md
Fixes a small issue in useGeoLocation doc that redirects to a wrong address for `useGeolocationEvents`
The change will point to correct path of useGeolocationEvents doc in useGeoLocation doc.
Faced it while going through docs for useGeolocation.
I tested it with Github's markdown preview.
=> Fix link to useGeolcationEvents in useGeolocation

docs/useDebouncedFn.md, src/useDebouncedFn.js
Fixed comment in useDebounceFn.js file according to value of wait parameter.
Fixed link from lodash.throttle to lodash.debounce in useDebounceFn.md file.
Related open issue: https://github.com/beautifulinteractions/beautiful-react-hooks/issues/178
Just fixing docs of that beautiful library.
=> [ci skip] :memo: fix comment and added right link to docs

src/utils/isAPISupported.js
When running SSR, any window-related hooks that call `isApiSupported` are failing because `window` is undefined.
This came up before as #63 and was fixed in #64 - but it looks like it was then re-broken 2 days later in #66
This allows a few key hooks (like useResizeObserver, etc) to exist in components that are rendered server-side, without crashing
I ran this locally
=> :bug: allow window to be undefined in api-support test

src/useResizeObserver.js
Hi, I noticed a weird bug when ref.current value is mutated the useResizeObserver hook stops working and only returns zeros. This is caused by incorrect use of useEffect hook that's point to the whole ref object instead of the current field.
It solves a problem where useResizeObserver stops working after the ref value is mutated. For example when the observed object is removed from DOM and then a new one is created in its place.
=> Observe elementRef.current instead of elementRef in useResizeObserver

src/useResizeObserver.js
* Dangling debounced callbacks are now canceled and don't throw "Can't perform a React state update on an unmounted component." error.
* ResizeObserver uses disconnect instead of unsubscribe. Before that, we could observe multiple elements but only unsubscribe from the last one when the component unmounts (potential memory leak).
Fixes https://github.com/beautifulinteractions/beautiful-react-hooks/issues/229
=> Cancel debounced callback + disconnect all observers

src/useViewportSpy.js
When the contents doesn't appear in the corresponding viewport anymore or once the contents have been seen by the user, the hook need to disconnect, otherwise, it will perform redundant rendering via state update on intersectionObserver.
fixes #234
=> Use viewport spy to disconnect early

src/useMediaQuery.js
MediaQueryList.addListener() is no longer recommended.
See https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
=> Using addEventListener instead of addListener that is deprecated

docs/useMouse.md
In  the global events example,  it is correct to `Avoid providing any argument to useMouse`. 
This fix referenced [useTouch's Global events example](https://beautifulinteractions.github.io/beautiful-react-hooks/#/useTouch).
I confirmed  that this example's code in [Live demo's VIEW CODE](https://beautifulinteractions.github.io/beautiful-react-hooks/#/useMouse) works.
=> fix: the Global events example in useMouse.md

CHANGELOG.md, package.json, src/useValueHistory.ts, test/useValueHistory.spec.js
fix useValueHistory bug when second parameter `distinct` set to `true` and update relevant test-case.
close #322
=> :bug: Fixing useValueHistory misuse of array.prototype.filter

src/useResizeObserver.ts
When using `useResizeObserver`, I discovered that the definition of the return type of this hook was misleading. `DOMRect` is initialized to `undefined`, and upon the first run of this hook, the return value can be undefined. In fact, the docs all show that you should check for the existence of `DOMRect` before doing anything with the return value. That should be reflected in the types.
Fixes #325 
TypeScript should be used to help consumers understand the potential values a variable could be. The return type of this function being inaccurate can cause consumers to inaccurately handle it and expect it to always be defined.
Linked locally into my project using this function and verified that it correctly reported that it was potentially undefined.
=> fix type definition on useResizeObserver

CHANGELOG.md, docs/Installation.md, package.json, src/shared/assignEventOnMount.ts, src/useDrag.ts, src/useDragEvents.ts, src/useDropZone.ts, src/useHorizontalSwipe.ts, src/useMouse.ts, src/useMouseEvents.ts, src/useMouseState.ts, src/useResizeObserver.ts, src/useSwipe.ts, src/useSwipeEvents.ts, src/useTouch.ts, src/useTouchEvents.ts, src/useTouchState.ts, src/useVerticalSwipe.ts, src/useViewportSpy.ts, test/useResizeObserver.spec.js
Related to #327, this PR fixes the types for all hooks the originally advertised using a `MutableRefObject`, when the expectation was that they would be React-managed refs, which should be a read-only ref, or `RefObject`. There are a couple places where I left MutableRefObject, because they were still appropriate uses of that type.
Fixes #327 
Ran verification, locally installed in my TS project to verify types are being reported correctly.
=> Update MutableRefObject to RefObject where appropriate

CHANGELOG.md, src/factory/createStorageHook.ts, test/useLocalStorage.spec.js, test/useSessionStorage.spec.js
Add error handling to the `useStorage` hooks
Examples of possible errors include `QuotaExceededError` errors if the storage runs out of space, or security related errors if the user disables access to the browser storage. Currently, these errors are unhandled by the `useStorage` hooks. 
I removed the `useEffect` so the `storedValue` state would only be set if the set browser storage call was successful. 
I've personally encountered `QuotaExceededError` errors resulting from the `useStorage` hooks' lack of error handling.
Added test cases for `setItem` and `getItem` errors to `useLocalStorage.spec.js` and `useSessionStorage.spec.js`
=> add error handling to use storage

CHANGELOG.md, src/factory/createStorageHook.ts, test/useLocalStorage.spec.js, test/useSessionStorage.spec.js
Add fix to set browser storage on initial render
In my previous change (https://github.com/antonioru/beautiful-react-hooks/pull/367) I removed the `useEffect` which in turn caused the browser storage not to be set on the initial render; this pr fixes that bug. 
I also added an update so that when `storage.setItem` throws an error in a `setValue` call, the `storedValue` state will still be set (previously the new state was not set). This is consistent with the behavior before https://github.com/antonioru/beautiful-react-hooks/pull/367, and with other similar `useStorage` hooks i.e. [UI.dev's hook](https://usehooks.com/useLocalStorage/)
I updated the types so the `storage` variable is correctly typed as `Storage`, which adds more type safety to the `storage.setItem` and `storage.getItem` …
=> add fix to set browser storage on initial render

CHANGELOG.md, src/factory/createStorageHook.ts
Wrap `setValue` from `useStorage` hook in `useCallback` to persist reference
This allows `setValue` to be added to a dependency array
=> wrap setValue from useStorage hook in useCallback to persist reference

docs/useSwipeEvents.md, src/useMouseEvents.ts, src/useSwipe.ts, src/useSwipeEvents.ts, src/useTouchEvents.ts
Not much to describe. For now, the user can decide if events should be passive or not
#258
#258
Via enabe/diable passive events and observe console result.
none
=> fix: allow user to change passive flag for change events

README.md, docs/README.es-ES.md, docs/README.it-IT.md, docs/README.jp-JP.md, docs/README.pl-PL.md, docs/README.pt-BR.md, docs/README.uk-UA.md, docs/README.zh-CN.md, docs/useDarkMode.md, docs/useIsFirstRender.md, docs/useUpdateEffect.md, src/useDarkMode.ts, src/useIsFirstRender.ts, src/useUpdateEffect.ts, test/mocks/MatchMediaQueryList.mock.js, test/useDarkMode.spec.js, test/useIsFirstRender.spec.js, test/useMediaQuery.spec.js, test/useUpdateEffect.spec.js
Basically looking at issues I've found one need for useDarkMode so I made it. To achieve this I've created 2 additional hooks `useIsFirstRender` and `useUpdateEffect`. The important thing to mention is that this hook uses a `prefers-color-scheme` to detect the user's operating system theme. Information about the user's dark mode is saved in the local storage. The hook is SSR safe and allows the user to manage dark mode via returned functions such as: `disable`, `enable` and `toggle`. To get access to the current dark mode state just destruct `isDarkMode` flag and that's it!
#317
#317
1. Test coverage,
2. Examples from docs, 
none
=> feat(hook): create useDarkMode hook

src/useInfiniteScroll.ts
> scrollTop is a non-rounded number, while scrollHeight and clientHeight are rounded — so the only way to determine if the scroll area is scrolled to the bottom is by seeing if the scroll amount is close enough to some threshold (in this example 1):
> 
> `Math.abs(element.scrollHeight - element.clientHeight - element.scrollTop) < 1`
> 
> The following will not work all the time because scrollTop can contain decimals:
> 
> `element.scrollHeight - Math.abs(element.scrollTop) === element.clientHeight`
[Source](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight)
=> Fix isBottom in the useInfiniteScroll

CHANGELOG.md, package.json, src/factory/createStorageHook.ts, test/useLocalStorage.spec.js, test/useSessionStorage.spec.js
Instead of using `storedValue` as a dependency within the `setValue` callback in `createStorageHook.ts` we are getting the current stored value from `setStoredValue` directly. This stops the `setValue` callback from unnecessarily being recreated every time the storedValue changes.
https://github.com/antonioru/beautiful-react-hooks/issues/395
I was getting an infinite loop when `setValue` was used as a dependency on a useEffect where the effect was calling `setValue`.
https://github.com/antonioru/beautiful-react-hooks/issues/395
Added additional unit tests.
=> 🐛  useLocalStorage no longer returns a new setValue function every time setValue is called

CHANGELOG.md, docs/useSpeechRecognition.md, src/useSpeechRecognition.ts, test/useSpeechRecognition.spec.js
=> useSpeechRecognition

src/useObjectState.ts
When giving useEffect the setState as dependance, it will rerun every time because we didn't use useCallback.
add useCallback to useObjectState to avoid redundant useEffect runs
dispatch of useReducer is consistent, as we can see [here](https://legacy.reactjs.org/docs/hooks-reference.html#usereducer:~:text=React%20guarantees%20that%20dispatch%20function%20identity%20is%20stable%20and%20won%E2%80%99t%20change%20on%20re%2Drenders.%20This%20is%20why%20it%E2%80%99s%20safe%20to%20omit%20from%20the%20useEffect%20or%20useCallback%20dependency%20list.).
=> add useCallback to useObjectState to avoid redundant useEffect runs

README.md, docs/useUnmount.md, docs/useWillUnmount.md, src/useUnmount.ts, src/useWillUnmount.ts, test/useUnmount.spec.js
- refactor(hook): useWillUnmount impl by useLayoutEffect
- feat(hook): add useUnmount replace origin-useWillUnmount
Originally, `useWillUnmount` lifecycle implementation was through useEffectClean, but React officially states that useEffectClean is executed after dom rendering, and obviously the name of the hook does not match the actual implementation
#414 
Correct lifecycle hook-name consistency with implementation
by - ./test/useWillUnmount.spec.js
- ./test/useUnmount.spec.js
=> refactor(hook): useWillUnmount impl by useLayoutEffect

package.json
Updated the react and react-dom peer dependency in `package.json` to "^18.2.0" to allow installation of later versions while maintaining compatibility with the package.
Fixes #423  
This change is necessary to address the issue of restricting the installation of later versions of React due to the exact version requirement in the peer dependency configuration of beautiful-react-hooks.
Conducted basic tests by running `npm test` and `npm build` to ensure that the package can still be built and tested successfully after updating the React peer dependency.
=> Update react and react-dom peer dependency to ^18.2.0
